// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obkpbpqotwqlqyhnpsvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ia3BicHFvdHdxbHF5aG5wc3ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTYzOTYsImV4cCI6MjA2MDk3MjM5Nn0.fa_JZ2wbAD2NrpcrmUUk8iKt4qBeOc8wXmzXxpfXkCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);